### ISSUE TITLE
Link not accessible: http://security.cs.rpi.edu/courses/binexp-spring2015/

### ISSUE THREAD

**Issue by karlosmid** [RPISEC/MBE#10]
Hi!
This link is not accessible. I am in Europe.
Is this expected?

**Comment by clarkb7** [comment]
No, it should be accessible, but that page is hosted on an RPI server. They auto-blacklist IPs, so it's possible your IP is blocked for some reason.

**Comment by raphui** [comment]
Link is still not accessible and I tried it with different IP. Any solution ?

**Comment by Lense** [comment]
Now it's actually down, for hardware issues. It should be up in the near future.

**Comment by raphui** [comment]
Ok, thanks :)
