### ISSUE TITLE
lab8B buffering

### ISSUE THREAD

**Issue by ykram** [RPISEC/MBE#11]
Is there any possibility of disabling line buffering for lab8B ? The way it currently is causes more headache than it's worth (imo) for solving this level via an automated way using pwntools.

**Comment by Lense** [comment]
The way I see it is that in the real world, not everything is going to buffer in just the way you want it to. The level is 100% solvable in its current state.  
  
Feel free to modify it so you can script it. These are, in the end, a learning resource, so do whatever will help you get the most out of it.

**Comment by ykram** [comment]
Fair enough. It caused issues at first but once I was able to work around them this no longer was an issue.
