### ISSUE TITLE
Git Rootfs

### ISSUE THREAD

**Issue by zachriggle** [RPISEC/MBE#2]
It looks like most of the effort in `setup_wargame.sh` and `external_tools.sh` is spent doing things which could be automated with a simple Git clone into the root directory.

```sh
root $ cd /
root $ git init
root $ git remote add origin https://github.com/RPISEC/MBE-rootfs 
root $ git checkout -f -t origin/master
```

This would automate the creation of all of the files and folders, and everything would be "ready to go".  The only scripting necessary would be to install a list of packages and fix permissions.

For an example of what this looks like, check out https://github.com/zachriggle/defcon22.

**Comment by RPISEC** [comment]
There is only one `cp` command (see line 320) to place the levels in the specified directory. Most of the work in setup_wargame.sh is locking down the machine, installing tools, creating users, and setting permissions.
