### ISSUE TITLE
ERROR: ./levels not found

### ISSUE THREAD

**Issue by adeptex** [RPISEC/MBE#25]
Hi guys. First of all - thanks for all your work, it's really an awesome project! 

When I try to install the Warzone after cloning the repo, I get 

> ERROR: ./levels not found

In order to install correctly, I had to rename the `src` dir to `levels`.

**Comment by clarkb7** [comment]
I assume you simply cloned the repo and ran setup_wargame.sh? 
The levels dir comes from our release archive as per the setup instructions. If you want to compile from source you'll have to run cmake as usual, first.

**Comment by clarkb7** [comment]
Closing this since there hasn't been a response is 3 weeks, feel free to re-open.
