### ISSUE TITLE
Next step after lab1C?

### ISSUE THREAD

**Issue by webhat** [RPISEC/MBE#28]
I just complete lab1C, and gained euid of lab1B. However to examine lab1B I need at least a egid of lab1B to execute the file.

Is there a trick I'm missing in the CTF?

**Comment by Lense** [comment]
See https://github.com/RPISEC/MBE#how-to-play

Once you complete one level, read the password of the next user. Then, log in as that user.

**Comment by webhat** [comment]
👍
