### ISSUE TITLE
can not access to website

### ISSUE THREAD

**Issue by jjjan** [RPISEC/MBE#3]
hello how can i access to this page? http://security.cs.rpi.edu/courses/binexp-spring2015/

it's forbidden or have any problem?

**Comment by gaasedelen** [comment]
The security.cs.rpi.edu server is down right now, we're working to bring it back online. Hopefully this will be resolved shortly.

That said, all the materials on the course website should be available in this repo and under releases (https://github.com/RPISEC/MBE/releases)

**Comment by jjjan** [comment]
great, thanks indeed is there any chance to have voice or video of slides?

**Comment by mcaniw** [comment]
Sadly there were no recordings of the lectures.

**Comment by ronanturner** [comment]
Only resources I couldn't find on this repository were the crackme files referenced in the slides - or am I mistaken? 

That said, these are terrific resources to be made freely available - thank you!

**Comment by gaasedelen** [comment]
I think those crackme's were for windows, so we didn't feel it would be super appropriate for the repo. We also had a Windows VM with IDA Free setup a few other tools setup which was not distributed. 

The course website is now back up, so I'm closing this issue.
