### ISSUE TITLE
gets and libc >= 2.23

### ISSUE THREAD

**Issue by ampotos** [RPISEC/MBE#31]
When I try to compile I have 1 error about the usage of gets a cpp file (and multiple warning on C file but it's ok for the prupose of this repo).

After looking rount a bit I found out I have a glibc 2.25 and in the changelog 2.23 of the glibc there is: 
* ISO C11 support:
+ do not declare gets.

I locally change it to fgets with a big size but maybe you want to fix it in another way.

**Comment by gaasedelen** [comment]
Thanks for the heads up. I don't expect we'll ever update the repo for these types of issues as we fully expected the levels to deprecate as the ecosystem evolved.

From [the readme](https://github.com/RPISEC/MBE#option-one---pre-made-warzone-vm)

> **As the years pass, compilers will change, security will improve, and the challenges in this repo may no longer be solvable.** Because of this, we have created a virtual machine disk image that closely replicates the universal Warzone wargame server we ran for the duration of this course. The VM has all the tools setup, challenges pre-compiled, and lab accounts ready to go. Hopefully it will endure the test of time.

We've always pushed hard for people to use the created VM as the entire environment has been setup in a nice little package. Alternatively, we also provided just the compiled binaries as a standalone archive on the releases page. 

Finally, if anyone still would _really_ like to re-compile the levels today, the easiest and most reliable option would probably be to do so somewhere on the provided VM. It will have the libraries and compilers from the days they were originally compiled :-)
