### ISSUE TITLE
MBE_VM not downloadable

### ISSUE THREAD

**Issue by cfossace** [RPISEC/MBE#33]
Is this only accessible via The Ark?

**Comment by Lense** [comment]
https://github.com/RPISEC/MBE/releases/download/v1.1_release/MBE_VM.vmdk.gz (linked in the README) is hosted on github and accessible from anywhere.

What link are you talking about, and where did you find it?

**Comment by cfossace** [comment]
It was that link, it wasn't downloading for some reason it said it would take 3 days.  I think Github was just having problems, because it works fine now.
