### ISSUE TITLE
Enabling ASLR in MBE_VM

### ISSUE THREAD

**Issue by igogo-x86** [RPISEC/MBE#34]
Looks like every account (gameadmin, lecture and labXX) has no enough privilege to enable ASLR. How it is supposed to be done?

**Comment by Lense** [comment]
gameadmin should have sudo access. Try running `sudo -i` to get a root shell, and then run the aslr commands.

If that doesn't work, could you describe how you set the VM up?

**Comment by igogo-x86** [comment]
That's worked, thanks!
