### ISSUE TITLE
Course website is down

### ISSUE THREAD

**Issue by hieplpvip** [RPISEC/MBE#44]
It looks like the course website is down.

**Comment by johnnyapol** [comment]
Hi @hieplpvip ,

Our university was recently the victim of a cyberattack and as a result a number of resources hosted on it are temporarily unavailable until service is restored. Ideally the website should be coming back up within the next couple of days but we don't have an exact timeframe.

**Comment by johnnyapol** [comment]
An archive is available on the Wayback machine in the meantime https://web.archive.org/web/20210402001507/security.cs.rpi.edu/courses/binexp-spring2015/

**Comment by johnnyapol** [comment]
Course website connectivity has been restored sometime in the past hour.
