### ISSUE TITLE
x64dbg

### ISSUE THREAD

**Issue by mrexodia** [RPISEC/MBE#5]
Might be useful to name as alternative to WinDBG for 64-bit on windows :)

**Comment by rojaster** [comment]
www.x86-64.org ?

**Comment by rojaster** [comment]
http://x64dbg.com ?

**Comment by mrexodia** [comment]
Hello, The website for x64dbg is http://x64dbg.com does that answer the
question?

**Comment by rojaster** [comment]
x64dbg is an alternative to WinDBG? I used to think it is alternative to Immunity or Olly, but not for kernel debugger like windbg.  am i wrong?

**Comment by XVilka** [comment]
@mrexodia @rojaster adding support of radare2 backend into the x64dbg would allow to use WinDBG protocol to connect the local or remote WinDBG instances. See more here https://github.com/radare/radare2/blob/master/doc/windbg and here (also PDB parsing) https://github.com/radare/radare2/blob/master/doc/pdb/pdb_usage

**Comment by mrexodia** [comment]
@rojaster x64dbg is a user mode-only debugger so in that sense it is not an alternative to WinDBG.

@XVilka At the moment there are no plans to add r2 as backend for x64dbg (plus its impossible with the current architecture), but I am looking at options for a full rewrite which might enable the architecture to switch between debugging engines.

**Comment by rojaster** [comment]
@mrexodia okey) and good news for the project) i will wait new stream))

**Comment by gaasedelen** [comment]
x64dbg is very cool. I find myself using it here and there, and had the class explored more in the space of windows we probably would have mentioned it. But if you could only learn one debugger on windows, I still advise it be WinDBG.

While the learning curve for WinDBG is higher, it has had a lot more time to mature into a solid, robust debugger. The more you grow familiar with it, the more you realize how versatile and feature rich it is. There also isn't really many options in the space of kernel land debugging. If our students could learn their way around WinDBG, then picking up x64dbg should be no problem.

Either way, the slides released here probably aren't going to be updated for any reason. This repo exists for the purposes of the levels. Possibly in future iterations of the class it will be included.
